### ISSUE TITLE
Create incidents on statuspage.io on failure

### ISSUE THREAD

**Issue by zelima** [datahq/datahub-emails#1]
We need the communication layer between statuspage.io and our services so that we can register an incident when any of automated datasets' processors fails so that we send Email notifying about it 

## Acceptance Criteria 

* [x] we have methods to register the incident
* [x] Method to subscribe a user to component 

## Tasks

* [x] `on_incident` method
  * [x] tests
* [x] `subscribe_user` method
  * [x] tests

**Comment by zelima** [comment]
FIXED
